include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  errors:
    strict_top_level_inference: ignore
    unused_element: ignore