name: khatoon_shared
description: "A new Flutter project."
version: 0.0.3
publish_to: none

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter          # ⬅️ اضافه شد
  intl: any               # می‌تواند بماند، اما بهتر است نسخه مشخص شود

  json_annotation: ^4.7.0
  latlong2: ^0.9.1
  freezed_annotation: ^2.1.0
  equatable: ^2.0.8
  event_bus: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.5
  build_runner: ^2.4.13        # منتقل شد
  json_serializable: ^6.8.0    # منتقل شد
  intl_utils: ^2.8.14          # منتقل شد (ابزار تولید کد)

flutter:
  uses-material-design: true
  generate: true