name: khatoon_shared
description: "A new Flutter project."
version: 0.0.3
publish_to: none

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter          # ⬅️ اضافه شد
  intl: any               # می‌تواند بماند، اما بهتر است نسخه مشخص شود

  json_annotation: ^4.7.0
  latlong2: ^0.9.1
  freezed_annotation: ^2.1.0
  equatable: ^2.0.8
  event_bus: ^2.0.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.5
  build_runner: ^2.4.13        # منتقل شد
  json_serializable: ^6.8.0    # منتقل شد
#  l10n_gen: ^1.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/avatar/
    - assets/phase2/
    - assets/tags/
    - assets/fonts/
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans.ttf

flutter_assets_generator:
  output_dir: generated/
  output_filename: assets
  class_name: Assets
  auto_detection: true
  # Automatically add missing dependencies (rive, flutter_svg, lottie) default: true
  auto_add_dependencies: true
  # Options: robust (default), legacy (old style)
  style: robust
  package_parameter_enabled: true
  named_with_parent: false
  path_ignore: [ ]
flutter_intl:
  enabled: true
