import 'package:json_annotation/json_annotation.dart';
import 'kala.dart';

part 'kala_model.g.dart';

@JsonSerializable()
class KalaModel extends Kala {
  const KalaModel({
    required super.id,
    required super.kalaName,
    required super.idSanjesh,
    required super.kalaType,
    super.properties,
    required super.idParent,
    required super.select,
    required super.mabFrosh,
    required super.minCount,
    required super.isDisabled,
    required super.isReserved,
    required super.idAnbarFrosh,
    super.attrib1,
    super.attrib2,
    super.attrib3,
    super.properties2,
    super.attrib4,
    super.attrib5,
    required super.idSanjesh2,
    required super.nSefaresh,
    super.propData1,
    super.propData2,
    super.propData3,
    super.propData4,
    super.propData5,
    super.propData6,
    super.propData7,
    required super.hasMaliat1,
    required super.hasMaliat2,
    required super.hasMaliat3,
    super.mabFrosh2,
    super.mabFrosh3,
    super.mabFrosh4,
    super.mabFrosh5,
    required super.takhfif1,
    required super.takhfif2,
    required super.takhfif3,
    required super.porsantDarsad,
    required super.idGroup1,
    required super.idGroup2,
    required super.idGroup3,
    required super.idGroup4,
    required super.mabKharid,
    required super.idAnbarKharid,
    required super.dateTimeChanged,
    required super.chandVahedi,
    required super.foodKalaType,
    required super.lastChange,
    required super.kalaType2,
    required super.mabFrosh1,
    required super.idPost,
    required super.mabKharidFinal,
    super.lastMabKharDate,
    super.quantity,
    required super.idKala,
    required super.barcode,
    super.barcodeOther,
    required super.state,
    required super.jozNesbat,
    required super.idBrand,
    required super.idHyper,
    super.sumFrosh,
    super.mabFroshOld1,
    super.mabFroshOld2,
    super.mabFroshMasraf,
    super.mabFrosh6,
    super.mabFrosh7,
    super.mabFrosh8,
    super.kharidCount,
    super.quantityMax,
    super.rozTasvieh,
    required super.idTaraf1,
    required super.idTarafType1,
    required super.idTaraf2,
    super.mabFroshOld1tk,
    super.mabFroshOld2tk,
    super.barcodJoz,
    super.mabModel,
    super.maliatDarsad1,
    super.maliatDarsad2,
    super.productDescription,
    super.productCreatedAt,
    super.productUnit,
  });

  factory KalaModel.fromJson(Map<String, dynamic> json) =>
      _$KalaModelFromJson(json);

  Map<String, dynamic> toJson() => _$KalaModelToJson(this);
}
