import 'package:json_annotation/json_annotation.dart';
import 'inf.dart';

part 'inf_model.g.dart';

@JsonSerializable()
class InfModel extends Inf {
  const InfModel({
    required super.id,
    required super.firstIdSanad,
    super.dbPath,
    required super.defVahed,
    required super.defKalaType,
    required super.isIdKalInc,
    super.coName,
    super.coAdd,
    super.coTel,
    super.coFax,
    super.maliName1,
    super.maliDarsad1,
    super.maliName2,
    super.maliDarsad2,
    super.maliName3,
    super.maliDarsad3,
    super.pavaraghi,
    super.coArmAdd,
    required super.isLeft,
    super.armImage,
    required super.sanadDesTitle,
    required super.isUserEqualSaller,
    required super.faktorAllBedShow,
    required super.faktorPorsantShow,
    required super.faktorKarmozdShow,
    required super.idKalaDigitMin,
    required super.isPishnahadShow,
    required super.isPorsantAuto,
    required super.isPorsantShowForAll,
    required super.isSanadChangeByUser,
    required super.isBedByCheck,
    required super.numberOfDayAccepted,
    super.shoar,
    required super.masoolAnbarHaz,
    required super.masoolFroshHaz,
    required super.idSanadDigitMin,
    required super.shahrCheckDef,
    required super.isAutoCheckActive,
    required super.isTasviehDateShowInFaktor,
    required super.isFaktorA5,
    required super.kalaCountDecimal,
    required super.faktorAnbarShow,
    required super.kalaAttrib1Def,
    required super.kalaAttrib2Def,
    required super.kalaAttrib3Def,
    required super.talaSoud,
    required super.talaMab18,
    required super.talaMab17,
    required super.talaMab16,
    required super.talaMab24,
    required super.enBarCode,
    required super.enAnbar,
    required super.enAccSanad,
    required super.enKalaSerial,
    required super.enTolid,
    required super.enSystemTry,
    required super.idTarafFrosh,
    required super.idTarafKharid,
    required super.froshNaghd,
    required super.dateReadOnly,
    required super.isKalaRepeat,
    required super.kharidNaghd,
    required super.faktorByArm,
    required super.repAllByArm,
    required super.roundByTakhfif,
    required super.dbChangeDate,
    required super.dbVer,
    required super.shoarCenter,
    required super.froshMabTypeToday,
    required super.isFroshMabTypeOnlyFree,
    required super.isShowTasviehTime,
    required super.darsadAlarmLastKharid,
    required super.firstIdFaktorFrosh,
    required super.firstIdFaktorKharid,
    required super.showKhCheckInHes,
    required super.sanadCountLoad,
    required super.maliat1TypeDef,
    required super.maliat2TypeDef,
    required super.maliat3TypeDef,
    required super.porsantTypeDef,
    required super.takhfifTypeDef,
    required super.isFroshFaktorFish,
    required super.faktorFroshType,
    required super.faktorKharidType,
    required super.enPorsant,
    required super.enMaliat1,
    required super.enMaliat2,
    required super.enMaliat1Kala,
    required super.enMaliat2Kala,
    required super.enPorsantKala,
    required super.enTakhfifKala,
    required super.enAghsat,
    required super.idPrintFrosh,
    required super.idPrintKharid,
    required super.anbarCheckInFaktor,
    required super.multiFaktor,
    required super.isCalSoudInFaktor,
    required super.isCalSoudInAmalKard,
    required super.enTabdil,
    required super.enHaml,
    required super.enMabFrosh,
    required super.enMultiSandoghUpdate,
    required super.editInFaktorFrosh,
    required super.enMabKharid,
    required super.barCodeDigitNum,
    required super.openKalaFromInKalaName,
    required super.propInFaktorCount,
    required super.sanadDetailProp2Title,
    required super.sanadDetailProp3Title,
    required super.isShowMabKharidKalaInFaktor,
    required super.enKalaGroup,
    required super.searchType,
    required super.enFroshMovaghat,
    required super.showKalaPropInFaktor,
    required super.showMabAfterSave,
    required super.openOtherFaktorAfterSave,
    required super.showMojodiInFaktor,
    required super.showLastMabKharidInFaktor,
    required super.showAvgMabKharidInFaktor,
    required super.idPrintFroshMovaghat,
    required super.mojodiManfi,
    required super.noLoadMojodiManfi,
    required super.movaghatToGhatei,
    required super.takhfifMsg,
    required super.showTakhfifMaliatKalaInFrosh,
    required super.showTakhfifMaliatKalaInKharid,
    required super.coMobile,
    required super.coCodeMelli,
    required super.coCodeEghtesadi,
    required super.coCodePosti,
    required super.coSabtNo,
    required super.kianAdd,
    required super.kianTelSales,
    required super.kianTelSupport,
    required super.kianEmailSupport1,
    required super.kianEmailSupport2,
    required super.coWebSite,
    required super.coEmail,
    required super.showMabWithTakhfifInFaktor,
    required super.idKalaBiggerFrom,
    required super.today,
    required super.settingInt1,
    required super.settingInt2,
    required super.settingInt3,
    required super.settingInt4,
    required super.settingDouble,
    required super.settingbit1,
    required super.settingbit2,
    required super.settingbit3,
    required super.settingbit4,
    required super.settingbit5,
    required super.settingString1,
    required super.settingString2,
    required super.settingString3,
    required super.settingString4,
    required super.mizCount,
    required super.enVahed2,
    required super.idKalaGroupDigit,
    required super.frosh,
    required super.kharid,
    required super.tolid,
    required super.masraf,
    required super.idKalaGroupDigit1,
    required super.frosh1,
    required super.kharid1,
    required super.tolid1,
    required super.masraf1,
    required super.project,
    required super.amani,
    required super.enMab,
    required super.enVahed21,
    required super.enAsnadTaiid,
    required super.enMabFrosh1,
    required super.repMojodiColumnCount,
    required super.anbarCheckInFaktor1,
    required super.sc,
    required super.idMarket,
    required super.idMarketAnbar,
    required super.updateTime,
    super.kpt,
    super.kpu,
    super.kpp,
    super.kpph,
    super.kpte,
    super.kptn,
    super.kpld,
    super.kppl,
    super.kped,
    super.kpuc,
    super.kplad,
  });

  factory InfModel.fromJson(Map<String, dynamic> json) =>
      _$InfModelFromJson(json);

  Map<String, dynamic> toJson() => _$InfModelToJson(this);
}
